{
  "pyprland": {
    "plugins": ["scratchpads", "monitors"]
  },
  "scratchpads": {
    "term": {
      "command": "kitty --class kitty-dropterm"
    }
  },
  "monitors": {
    "placement": {
      "SB2": {
        "topOf": "eDP-1"
      }
    },
    "unknown": "wlrlui"
  }
}
